# Generated by Django 5.1.1 on 2024-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymDetails', '0003_alter_gyminfo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gyminfo',
            name='owner_name',
        ),
    ]
