# Generated by Django 5.1.1 on 2024-10-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymDetails', '0004_remove_gyminfo_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gyminfo',
            name='mobile_phone',
        ),
    ]
